version: 2

updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      k8s.io:
        patterns:
          - "k8s.io/api"
          - "k8s.io/apiextensions-apiserver"
          - "k8s.io/apimachinery"
          - "k8s.io/apiserver"
          - "k8s.io/cli-runtime"
          - "k8s.io/client-go"
          - "k8s.io/kubectl"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
