SETUP_GOTOOLS := @echo "Installing golint and vet" && go get -u github.com/golang/lint/golint && go get -u -v golang.org/x/tools/cmd/vet
GO_VET := @echo "Running go vet ..." && go vet ./...
GO_LINT := @echo "Running golint ..." && golint ./...
GO_TEST := @echo "Running tests ..." && go test -v ./...
