/*
Copyright The Helm Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"os"
	"slices"

	apiextensionsv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	apiextensionsv1beta1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1"
	"k8s.io/apimachinery/pkg/runtime"
	clientgoscheme "k8s.io/client-go/kubernetes/scheme"
)

const licenseHeader = `/*
Copyright The Helm Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/`

func main() {
	output := flag.String("output", "default_versions.go", "path to the generated Go file")
	flag.Parse()

	versions, err := knownVersions()
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}

	var source bytes.Buffer
	fmt.Fprintln(&source, licenseHeader)
	fmt.Fprintln(&source)
	fmt.Fprintln(&source, "// Code generated by gendefaultversions; DO NOT EDIT.")
	fmt.Fprintln(&source)
	fmt.Fprintln(&source, "package common")
	fmt.Fprintln(&source)
	fmt.Fprintln(&source, "// DefaultVersionSet is the default set of Kubernetes API versions used")
	fmt.Fprintln(&source, "// when Helm renders without live cluster discovery.")
	fmt.Fprintln(&source, "//")
	fmt.Fprintln(&source, "// This is a snapshot of the API versions registered by Helm's Kubernetes")
	fmt.Fprintln(&source, "// dependencies, not a list of APIs served by every supported cluster. Live")
	fmt.Fprintln(&source, "// cluster operations build Capabilities from server discovery instead.")
	fmt.Fprintln(&source, "//")
	fmt.Fprintln(&source, "// Review API additions and removals against the Kubernetes versions supported")
	fmt.Fprintln(&source, "// by this Helm release before committing a regenerated snapshot.")
	fmt.Fprintln(&source, "//")
	fmt.Fprintln(&source, "// Regenerate after updating Kubernetes dependencies with:")
	fmt.Fprintln(&source, "//")
	fmt.Fprintln(&source, "//\tgo generate ./pkg/chart/common")
	fmt.Fprintln(&source, "var DefaultVersionSet = VersionSet{")
	for _, version := range versions {
		fmt.Fprintf(&source, "\t%q,\n", version)
	}
	fmt.Fprintln(&source, "}")

	formatted, err := format.Source(source.Bytes())
	if err != nil {
		fmt.Fprintf(os.Stderr, "format generated source: %v\n", err)
		os.Exit(1)
	}
	if err := os.WriteFile(*output, formatted, 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "write generated source: %v\n", err)
		os.Exit(1)
	}
}

func knownVersions() ([]string, error) {
	scheme := runtime.NewScheme()
	if err := clientgoscheme.AddToScheme(scheme); err != nil {
		return nil, fmt.Errorf("register client-go scheme: %w", err)
	}
	if err := apiextensionsv1beta1.AddToScheme(scheme); err != nil {
		return nil, fmt.Errorf("register apiextensions v1beta1 scheme: %w", err)
	}
	if err := apiextensionsv1.AddToScheme(scheme); err != nil {
		return nil, fmt.Errorf("register apiextensions v1 scheme: %w", err)
	}

	groupSet := make(map[string]struct{})
	for _, groupVersion := range scheme.PrioritizedVersionsAllGroups() {
		groupSet[groupVersion.Group] = struct{}{}
	}
	groups := make([]string, 0, len(groupSet))
	for group := range groupSet {
		groups = append(groups, group)
	}
	slices.Sort(groups)

	versions := make([]string, 0)
	for _, group := range groups {
		for _, groupVersion := range scheme.PrioritizedVersionsForGroup(group) {
			versions = append(versions, groupVersion.String())
		}
	}
	return versions, nil
}
