/*
Copyright The Helm Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package main

import (
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"

	"helm.sh/helm/v3/pkg/chart"
	"helm.sh/helm/v3/pkg/chart/loader"

	"github.com/pkg/errors"
	"github.com/spf13/cobra"

	"helm.sh/helm/v3/pkg/action"
	"helm.sh/helm/v3/pkg/chartutil"
	"helm.sh/helm/v3/pkg/cli/values"
	"helm.sh/helm/v3/pkg/getter"
	"helm.sh/helm/v3/pkg/lint/support"
)

const globalKey = "global"

var longLintHelp = `
This command takes a path to a chart and runs a series of tests to verify that
the chart is well-formed.

If the linter encounters things that will cause the chart to fail installation,
it will emit [ERROR] messages. If it encounters issues that break with convention
or recommendation, it will emit [WARNING] messages.
`

type scopedChart struct {
	path string
	root bool
}

type parentScope struct {
	metadata *chart.Metadata
	values   map[string]interface{}
}

func newLintCmd(out io.Writer) *cobra.Command {
	client := action.NewLint()
	valueOpts := &values.Options{}
	var kubeVersion string

	cmd := &cobra.Command{
		Use:   "lint PATH",
		Short: "examine a chart for possible issues",
		Long:  longLintHelp,
		RunE: func(_ *cobra.Command, args []string) error {
			if len(args) > 1 {
				return fmt.Errorf("invalid call, expected path to a single chart, got: %s", args)
			}
			charts := []scopedChart{{".", true}}
			root := &parentScope{}
			if len(args) > 0 {
				charts[0].path = args[0]
			}

			if kubeVersion != "" {
				parsedKubeVersion, err := chartutil.ParseKubeVersion(kubeVersion)
				if err != nil {
					return fmt.Errorf("invalid kube version '%s': %s", kubeVersion, err)
				}
				client.KubeVersion = parsedKubeVersion
			}
			client.Namespace = settings.Namespace()
			vals, err := valueOpts.MergeValues(getter.All(settings))
			if err != nil {
				return err
			}

			if client.WithSubcharts {
				// load root chart metadata & chart values to prepare values for sub-charts
				root.metadata, _ = chartutil.LoadChartfile(filepath.Join(charts[0].path, "Chart.yaml"))
				root.values, _ = chartutil.ReadValuesFile(filepath.Join(charts[0].path, "values.yaml"))
				root.values = chartutil.CoalesceTables(root.values, vals)

				filepath.Walk(filepath.Join(charts[0].path, "charts"), func(path string, info os.FileInfo, _ error) error {
					if info != nil {
						if info.Name() == "Chart.yaml" {
							charts = append(charts, scopedChart{filepath.Dir(path), false})
						} else if strings.HasSuffix(path, ".tgz") || strings.HasSuffix(path, ".tar.gz") {
							charts = append(charts, scopedChart{path, false})
						}
					}
					return nil
				})
			}

			var message strings.Builder
			failed := 0
			errorsOrWarnings := 0
			linted := 0

			for _, single := range charts {
				for scope, scopedVals := range getScopedValues(root, single, vals) {
					linted++
					result := client.Run([]string{single.path}, scopedVals)

					// If there is no errors/warnings and quiet flag is set
					// go to the next chart
					hasWarningsOrErrors := action.HasWarningsOrErrors(result)
					if hasWarningsOrErrors {
						errorsOrWarnings++
					}
					if client.Quiet && !hasWarningsOrErrors {
						continue
					}

					fmt.Fprintf(&message, "==> Linting %s (scope: %s)\n", single.path, scope)

					// All the Errors that are generated by a chart
					// that failed a lint will be included in the
					// results.Messages so we only need to print
					// the Errors if there are no Messages.
					if len(result.Messages) == 0 {
						for _, err := range result.Errors {
							fmt.Fprintf(&message, "Error %s\n", err)
						}
					}

					for _, msg := range result.Messages {
						if !client.Quiet || msg.Severity > support.InfoSev {
							fmt.Fprintf(&message, "%s\n", msg)
						}
					}

					if len(result.Errors) != 0 {
						failed++
					}

					// Adding extra new line here to break up the
					// results, stops this from being a big wall of
					// text and makes it easier to follow.
					fmt.Fprint(&message, "\n")
				}
			}

			fmt.Fprint(out, message.String())

			summary := fmt.Sprintf("%d chart(s) linted, %d chart(s) failed", linted, failed)
			if failed > 0 {
				return errors.New(summary)
			}
			if !client.Quiet || errorsOrWarnings > 0 {
				fmt.Fprintln(out, summary)
			}
			return nil
		},
	}

	f := cmd.Flags()
	f.BoolVar(&client.Strict, "strict", false, "fail on lint warnings")
	f.BoolVar(&client.WithSubcharts, "with-subcharts", false, "lint dependent charts")
	f.BoolVar(&client.Quiet, "quiet", false, "print only warnings and errors")
	f.StringVar(&kubeVersion, "kube-version", "", "Kubernetes version used for capabilities and deprecation checks")
	addValueOptionsFlags(f, valueOpts)

	return cmd
}

func getScopedValues(parent *parentScope, single scopedChart, vals chartutil.Values) map[string]chartutil.Values {
	if single.root {
		return map[string]chartutil.Values{"root": vals}
	}
	result := map[string]chartutil.Values{}
	if parent.metadata != nil {
		// try to load dependent chart and match it with parent definition of dependencies
		if subChart, err := loader.Load(single.path); err == nil {
			for _, dependency := range parent.metadata.Dependencies {
				// it is worth remembering that there could be the same sub-chart used in many dependencies
				// to handle this we should validate such sub-chart as many times (with the appropriate set of values)
				// aa it is defined in the parent chart
				if subChart.Metadata.Version == dependency.Version && subChart.Name() == dependency.Name {
					alias := dependency.Alias
					if alias == "" {
						alias = dependency.Name
					}
					tmp := chartutil.Values{}
					if _, ok := parent.values[alias]; ok {
						tmp = parent.values[alias].(map[string]interface{})
					}
					if _, ok := parent.values[globalKey]; ok {
						tmp[globalKey] = parent.values[globalKey].(map[string]interface{})
					}
					result[alias] = tmp
				}
			}
		}
	}
	// if we can't find any suitable values, just provide an empty set for sub-chart to at least validate other aspects
	if len(result) == 0 {
		result["empty"] = chartutil.Values{}
	}
	return result
}
