// Code generated by protoc-gen-go.
// source: hapi/release/modules.proto
// DO NOT EDIT!

package release

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Result_Status int32

const (
	// No status set
	Result_UNKNOWN Result_Status = 0
	// Operation was successful
	Result_SUCCESS Result_Status = 1
	// Operation had no results (e.g. upgrade identical, rollback to same, delete non-existent)
	Result_UNCHANGED Result_Status = 2
	// Operation failed
	Result_ERROR Result_Status = 3
)

var Result_Status_name = map[int32]string{
	0: "UNKNOWN",
	1: "SUCCESS",
	2: "UNCHANGED",
	3: "ERROR",
}
var Result_Status_value = map[string]int32{
	"UNKNOWN":   0,
	"SUCCESS":   1,
	"UNCHANGED": 2,
	"ERROR":     3,
}

func (x Result_Status) String() string {
	return proto.EnumName(Result_Status_name, int32(x))
}
func (Result_Status) EnumDescriptor() ([]byte, []int) { return fileDescriptor2, []int{0, 0} }

type Result struct {
	Info string   `protobuf:"bytes,1,opt,name=info" json:"info,omitempty"`
	Log  []string `protobuf:"bytes,2,rep,name=log" json:"log,omitempty"`
}

func (m *Result) Reset()                    { *m = Result{} }
func (m *Result) String() string            { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()               {}
func (*Result) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

type VersionReleaseRequest struct {
}

func (m *VersionReleaseRequest) Reset()                    { *m = VersionReleaseRequest{} }
func (m *VersionReleaseRequest) String() string            { return proto.CompactTextString(m) }
func (*VersionReleaseRequest) ProtoMessage()               {}
func (*VersionReleaseRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{1} }

type VersionReleaseResponse struct {
	Name    string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Version string `protobuf:"bytes,2,opt,name=version" json:"version,omitempty"`
}

func (m *VersionReleaseResponse) Reset()                    { *m = VersionReleaseResponse{} }
func (m *VersionReleaseResponse) String() string            { return proto.CompactTextString(m) }
func (*VersionReleaseResponse) ProtoMessage()               {}
func (*VersionReleaseResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{2} }

type InstallReleaseRequest struct {
	Release *Release `protobuf:"bytes,1,opt,name=release" json:"release,omitempty"`
}

func (m *InstallReleaseRequest) Reset()                    { *m = InstallReleaseRequest{} }
func (m *InstallReleaseRequest) String() string            { return proto.CompactTextString(m) }
func (*InstallReleaseRequest) ProtoMessage()               {}
func (*InstallReleaseRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{3} }

func (m *InstallReleaseRequest) GetRelease() *Release {
	if m != nil {
		return m.Release
	}
	return nil
}

type InstallReleaseResponse struct {
	Release *Release `protobuf:"bytes,1,opt,name=release" json:"release,omitempty"`
	Result  *Result  `protobuf:"bytes,2,opt,name=result" json:"result,omitempty"`
}

func (m *InstallReleaseResponse) Reset()                    { *m = InstallReleaseResponse{} }
func (m *InstallReleaseResponse) String() string            { return proto.CompactTextString(m) }
func (*InstallReleaseResponse) ProtoMessage()               {}
func (*InstallReleaseResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{4} }

func (m *InstallReleaseResponse) GetRelease() *Release {
	if m != nil {
		return m.Release
	}
	return nil
}

func (m *InstallReleaseResponse) GetResult() *Result {
	if m != nil {
		return m.Result
	}
	return nil
}

type DeleteReleaseRequest struct {
	Release *Release `protobuf:"bytes,1,opt,name=release" json:"release,omitempty"`
}

func (m *DeleteReleaseRequest) Reset()                    { *m = DeleteReleaseRequest{} }
func (m *DeleteReleaseRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteReleaseRequest) ProtoMessage()               {}
func (*DeleteReleaseRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{5} }

func (m *DeleteReleaseRequest) GetRelease() *Release {
	if m != nil {
		return m.Release
	}
	return nil
}

type DeleteReleaseResponse struct {
	Release *Release `protobuf:"bytes,1,opt,name=release" json:"release,omitempty"`
	Result  *Result  `protobuf:"bytes,2,opt,name=result" json:"result,omitempty"`
}

func (m *DeleteReleaseResponse) Reset()                    { *m = DeleteReleaseResponse{} }
func (m *DeleteReleaseResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteReleaseResponse) ProtoMessage()               {}
func (*DeleteReleaseResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{6} }

func (m *DeleteReleaseResponse) GetRelease() *Release {
	if m != nil {
		return m.Release
	}
	return nil
}

func (m *DeleteReleaseResponse) GetResult() *Result {
	if m != nil {
		return m.Result
	}
	return nil
}

type UpgradeReleaseRequest struct {
	Current  *Release `protobuf:"bytes,1,opt,name=current" json:"current,omitempty"`
	Target   *Release `protobuf:"bytes,2,opt,name=target" json:"target,omitempty"`
	Timeout  int64    `protobuf:"varint,3,opt,name=Timeout" json:"Timeout,omitempty"`
	Wait     bool     `protobuf:"varint,4,opt,name=Wait" json:"Wait,omitempty"`
	Recreate bool     `protobuf:"varint,5,opt,name=Recreate" json:"Recreate,omitempty"`
}

func (m *UpgradeReleaseRequest) Reset()                    { *m = UpgradeReleaseRequest{} }
func (m *UpgradeReleaseRequest) String() string            { return proto.CompactTextString(m) }
func (*UpgradeReleaseRequest) ProtoMessage()               {}
func (*UpgradeReleaseRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{7} }

func (m *UpgradeReleaseRequest) GetCurrent() *Release {
	if m != nil {
		return m.Current
	}
	return nil
}

func (m *UpgradeReleaseRequest) GetTarget() *Release {
	if m != nil {
		return m.Target
	}
	return nil
}

type UpgradeReleaseResponse struct {
	Release *Release `protobuf:"bytes,1,opt,name=release" json:"release,omitempty"`
	Result  *Result  `protobuf:"bytes,2,opt,name=result" json:"result,omitempty"`
}

func (m *UpgradeReleaseResponse) Reset()                    { *m = UpgradeReleaseResponse{} }
func (m *UpgradeReleaseResponse) String() string            { return proto.CompactTextString(m) }
func (*UpgradeReleaseResponse) ProtoMessage()               {}
func (*UpgradeReleaseResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{8} }

func (m *UpgradeReleaseResponse) GetRelease() *Release {
	if m != nil {
		return m.Release
	}
	return nil
}

func (m *UpgradeReleaseResponse) GetResult() *Result {
	if m != nil {
		return m.Result
	}
	return nil
}

type RollbackReleaseRequest struct {
	Current  *Release `protobuf:"bytes,1,opt,name=current" json:"current,omitempty"`
	Target   *Release `protobuf:"bytes,2,opt,name=target" json:"target,omitempty"`
	Timeout  int64    `protobuf:"varint,3,opt,name=Timeout" json:"Timeout,omitempty"`
	Wait     bool     `protobuf:"varint,4,opt,name=Wait" json:"Wait,omitempty"`
	Recreate bool     `protobuf:"varint,5,opt,name=Recreate" json:"Recreate,omitempty"`
}

func (m *RollbackReleaseRequest) Reset()                    { *m = RollbackReleaseRequest{} }
func (m *RollbackReleaseRequest) String() string            { return proto.CompactTextString(m) }
func (*RollbackReleaseRequest) ProtoMessage()               {}
func (*RollbackReleaseRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{9} }

func (m *RollbackReleaseRequest) GetCurrent() *Release {
	if m != nil {
		return m.Current
	}
	return nil
}

func (m *RollbackReleaseRequest) GetTarget() *Release {
	if m != nil {
		return m.Target
	}
	return nil
}

type RollbackReleaseResponse struct {
	Release *Release `protobuf:"bytes,1,opt,name=release" json:"release,omitempty"`
	Result  *Result  `protobuf:"bytes,2,opt,name=result" json:"result,omitempty"`
}

func (m *RollbackReleaseResponse) Reset()                    { *m = RollbackReleaseResponse{} }
func (m *RollbackReleaseResponse) String() string            { return proto.CompactTextString(m) }
func (*RollbackReleaseResponse) ProtoMessage()               {}
func (*RollbackReleaseResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{10} }

func (m *RollbackReleaseResponse) GetRelease() *Release {
	if m != nil {
		return m.Release
	}
	return nil
}

func (m *RollbackReleaseResponse) GetResult() *Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func init() {
	proto.RegisterType((*Result)(nil), "hapi.release.Result")
	proto.RegisterType((*VersionReleaseRequest)(nil), "hapi.release.VersionReleaseRequest")
	proto.RegisterType((*VersionReleaseResponse)(nil), "hapi.release.VersionReleaseResponse")
	proto.RegisterType((*InstallReleaseRequest)(nil), "hapi.release.InstallReleaseRequest")
	proto.RegisterType((*InstallReleaseResponse)(nil), "hapi.release.InstallReleaseResponse")
	proto.RegisterType((*DeleteReleaseRequest)(nil), "hapi.release.DeleteReleaseRequest")
	proto.RegisterType((*DeleteReleaseResponse)(nil), "hapi.release.DeleteReleaseResponse")
	proto.RegisterType((*UpgradeReleaseRequest)(nil), "hapi.release.UpgradeReleaseRequest")
	proto.RegisterType((*UpgradeReleaseResponse)(nil), "hapi.release.UpgradeReleaseResponse")
	proto.RegisterType((*RollbackReleaseRequest)(nil), "hapi.release.RollbackReleaseRequest")
	proto.RegisterType((*RollbackReleaseResponse)(nil), "hapi.release.RollbackReleaseResponse")
	proto.RegisterEnum("hapi.release.Result_Status", Result_Status_name, Result_Status_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for ReleaseModuleService service

type ReleaseModuleServiceClient interface {
	Version(ctx context.Context, in *VersionReleaseRequest, opts ...grpc.CallOption) (*VersionReleaseResponse, error)
	// InstallRelease requests installation of a chart as a new release.
	InstallRelease(ctx context.Context, in *InstallReleaseRequest, opts ...grpc.CallOption) (*InstallReleaseResponse, error)
	// DeleteRelease requests deletion of a named release.
	DeleteRelease(ctx context.Context, in *DeleteReleaseRequest, opts ...grpc.CallOption) (*DeleteReleaseResponse, error)
	// RollbackRelease rolls back a release to a previous version.
	RollbackRelease(ctx context.Context, in *RollbackReleaseRequest, opts ...grpc.CallOption) (*RollbackReleaseResponse, error)
	// UpgradeRelease updates release content.
	UpgradeRelease(ctx context.Context, in *UpgradeReleaseRequest, opts ...grpc.CallOption) (*UpgradeReleaseResponse, error)
}

type releaseModuleServiceClient struct {
	cc *grpc.ClientConn
}

func NewReleaseModuleServiceClient(cc *grpc.ClientConn) ReleaseModuleServiceClient {
	return &releaseModuleServiceClient{cc}
}

func (c *releaseModuleServiceClient) Version(ctx context.Context, in *VersionReleaseRequest, opts ...grpc.CallOption) (*VersionReleaseResponse, error) {
	out := new(VersionReleaseResponse)
	err := grpc.Invoke(ctx, "/hapi.release.ReleaseModuleService/Version", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *releaseModuleServiceClient) InstallRelease(ctx context.Context, in *InstallReleaseRequest, opts ...grpc.CallOption) (*InstallReleaseResponse, error) {
	out := new(InstallReleaseResponse)
	err := grpc.Invoke(ctx, "/hapi.release.ReleaseModuleService/InstallRelease", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *releaseModuleServiceClient) DeleteRelease(ctx context.Context, in *DeleteReleaseRequest, opts ...grpc.CallOption) (*DeleteReleaseResponse, error) {
	out := new(DeleteReleaseResponse)
	err := grpc.Invoke(ctx, "/hapi.release.ReleaseModuleService/DeleteRelease", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *releaseModuleServiceClient) RollbackRelease(ctx context.Context, in *RollbackReleaseRequest, opts ...grpc.CallOption) (*RollbackReleaseResponse, error) {
	out := new(RollbackReleaseResponse)
	err := grpc.Invoke(ctx, "/hapi.release.ReleaseModuleService/RollbackRelease", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *releaseModuleServiceClient) UpgradeRelease(ctx context.Context, in *UpgradeReleaseRequest, opts ...grpc.CallOption) (*UpgradeReleaseResponse, error) {
	out := new(UpgradeReleaseResponse)
	err := grpc.Invoke(ctx, "/hapi.release.ReleaseModuleService/UpgradeRelease", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ReleaseModuleService service

type ReleaseModuleServiceServer interface {
	Version(context.Context, *VersionReleaseRequest) (*VersionReleaseResponse, error)
	// InstallRelease requests installation of a chart as a new release.
	InstallRelease(context.Context, *InstallReleaseRequest) (*InstallReleaseResponse, error)
	// DeleteRelease requests deletion of a named release.
	DeleteRelease(context.Context, *DeleteReleaseRequest) (*DeleteReleaseResponse, error)
	// RollbackRelease rolls back a release to a previous version.
	RollbackRelease(context.Context, *RollbackReleaseRequest) (*RollbackReleaseResponse, error)
	// UpgradeRelease updates release content.
	UpgradeRelease(context.Context, *UpgradeReleaseRequest) (*UpgradeReleaseResponse, error)
}

func RegisterReleaseModuleServiceServer(s *grpc.Server, srv ReleaseModuleServiceServer) {
	s.RegisterService(&_ReleaseModuleService_serviceDesc, srv)
}

func _ReleaseModuleService_Version_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VersionReleaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReleaseModuleServiceServer).Version(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hapi.release.ReleaseModuleService/Version",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReleaseModuleServiceServer).Version(ctx, req.(*VersionReleaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReleaseModuleService_InstallRelease_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstallReleaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReleaseModuleServiceServer).InstallRelease(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hapi.release.ReleaseModuleService/InstallRelease",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReleaseModuleServiceServer).InstallRelease(ctx, req.(*InstallReleaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReleaseModuleService_DeleteRelease_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteReleaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReleaseModuleServiceServer).DeleteRelease(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hapi.release.ReleaseModuleService/DeleteRelease",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReleaseModuleServiceServer).DeleteRelease(ctx, req.(*DeleteReleaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReleaseModuleService_RollbackRelease_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RollbackReleaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReleaseModuleServiceServer).RollbackRelease(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hapi.release.ReleaseModuleService/RollbackRelease",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReleaseModuleServiceServer).RollbackRelease(ctx, req.(*RollbackReleaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReleaseModuleService_UpgradeRelease_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpgradeReleaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReleaseModuleServiceServer).UpgradeRelease(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hapi.release.ReleaseModuleService/UpgradeRelease",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReleaseModuleServiceServer).UpgradeRelease(ctx, req.(*UpgradeReleaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ReleaseModuleService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "hapi.release.ReleaseModuleService",
	HandlerType: (*ReleaseModuleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Version",
			Handler:    _ReleaseModuleService_Version_Handler,
		},
		{
			MethodName: "InstallRelease",
			Handler:    _ReleaseModuleService_InstallRelease_Handler,
		},
		{
			MethodName: "DeleteRelease",
			Handler:    _ReleaseModuleService_DeleteRelease_Handler,
		},
		{
			MethodName: "RollbackRelease",
			Handler:    _ReleaseModuleService_RollbackRelease_Handler,
		},
		{
			MethodName: "UpgradeRelease",
			Handler:    _ReleaseModuleService_UpgradeRelease_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor2,
}

func init() { proto.RegisterFile("hapi/release/modules.proto", fileDescriptor2) }

var fileDescriptor2 = []byte{
	// 523 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xd4, 0x55, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x8d, 0xe3, 0x36, 0xa9, 0x27, 0x14, 0xac, 0x55, 0x9c, 0x5a, 0x3e, 0x45, 0x5b, 0x90, 0x72,
	0x80, 0x44, 0x0a, 0x57, 0x2e, 0x90, 0x86, 0x16, 0x21, 0x5c, 0x69, 0x4d, 0x5a, 0xa9, 0x12, 0x12,
	0xdb, 0x74, 0x08, 0x16, 0x1b, 0x3b, 0xac, 0xd7, 0x81, 0xdf, 0x83, 0xcf, 0xe1, 0x2b, 0x90, 0x1d,
	0xbb, 0xaa, 0x17, 0xd3, 0x0a, 0x21, 0x45, 0xea, 0x29, 0x33, 0x9e, 0x97, 0xb7, 0x33, 0xcf, 0xb3,
	0xcf, 0xe0, 0x7d, 0xe6, 0xab, 0x70, 0x24, 0x51, 0x20, 0x4f, 0x70, 0xb4, 0x8c, 0xaf, 0x52, 0x81,
	0xc9, 0x70, 0x25, 0x63, 0x15, 0x93, 0x07, 0x59, 0x6d, 0x58, 0xd4, 0xbc, 0x2a, 0xb2, 0xf8, 0xdd,
	0x20, 0xa9, 0x80, 0x16, 0xc3, 0x24, 0x15, 0x8a, 0x10, 0xd8, 0x09, 0xa3, 0x4f, 0xb1, 0x6b, 0xf4,
	0x8d, 0x81, 0xc5, 0xf2, 0x98, 0xd8, 0x60, 0x8a, 0x78, 0xe1, 0x36, 0xfb, 0xe6, 0xc0, 0x62, 0x59,
	0x48, 0x5f, 0x40, 0x2b, 0x50, 0x5c, 0xa5, 0x09, 0xe9, 0x40, 0x7b, 0xe6, 0xbf, 0xf5, 0x4f, 0xcf,
	0x7d, 0xbb, 0x91, 0x25, 0xc1, 0x6c, 0x32, 0x99, 0x06, 0x81, 0x6d, 0x90, 0x7d, 0xb0, 0x66, 0xfe,
	0xe4, 0xe4, 0xa5, 0x7f, 0x3c, 0x3d, 0xb2, 0x9b, 0xc4, 0x82, 0xdd, 0x29, 0x63, 0xa7, 0xcc, 0x36,
	0xe9, 0x01, 0x38, 0x67, 0x28, 0x93, 0x30, 0x8e, 0xd8, 0xa6, 0x0b, 0x86, 0x5f, 0x53, 0x4c, 0x14,
	0x7d, 0x0d, 0x3d, 0xbd, 0x90, 0xac, 0xe2, 0x28, 0xc1, 0xac, 0xad, 0x88, 0x2f, 0xb1, 0x6c, 0x2b,
	0x8b, 0x89, 0x0b, 0xed, 0xf5, 0x06, 0xed, 0x36, 0xf3, 0xc7, 0x65, 0x4a, 0x4f, 0xc0, 0x79, 0x13,
	0x25, 0x8a, 0x0b, 0x51, 0x3d, 0x80, 0x8c, 0xa0, 0x5d, 0x0c, 0x9e, 0x33, 0x75, 0xc6, 0xce, 0xf0,
	0xa6, 0x46, 0xc3, 0x12, 0x5e, 0xa2, 0xe8, 0x37, 0xe8, 0xe9, 0x4c, 0x45, 0x47, 0xff, 0x4a, 0x45,
	0x9e, 0x42, 0x4b, 0xe6, 0x1a, 0xe7, 0xdd, 0x76, 0xc6, 0x5d, 0x1d, 0x9f, 0xd5, 0x58, 0x81, 0xa1,
	0xc7, 0xd0, 0x3d, 0x42, 0x81, 0x0a, 0xff, 0x77, 0x82, 0x35, 0x38, 0x1a, 0xd1, 0x76, 0x06, 0xf8,
	0x61, 0x80, 0x33, 0x5b, 0x2d, 0x24, 0xbf, 0xaa, 0x19, 0x61, 0x9e, 0x4a, 0x89, 0x91, 0xba, 0xe3,
	0xe0, 0x02, 0x45, 0x9e, 0x41, 0x4b, 0x71, 0xb9, 0xc0, 0xf2, 0xe0, 0xbf, 0xe0, 0x0b, 0x50, 0xb6,
	0x17, 0xef, 0xc3, 0x25, 0xc6, 0xa9, 0x72, 0xcd, 0xbe, 0x31, 0x30, 0x59, 0x99, 0x66, 0x5b, 0x74,
	0xce, 0x43, 0xe5, 0xee, 0xf4, 0x8d, 0xc1, 0x1e, 0xcb, 0x63, 0xe2, 0xc1, 0x1e, 0xc3, 0xb9, 0x44,
	0xae, 0xd0, 0xdd, 0xcd, 0x9f, 0x5f, 0xe7, 0xd9, 0xdb, 0xd7, 0x47, 0xd8, 0x8e, 0x78, 0x3f, 0x0d,
	0xe8, 0xb1, 0x58, 0x88, 0x4b, 0x3e, 0xff, 0x72, 0x6f, 0xd5, 0xfb, 0x0e, 0x07, 0x7f, 0xcc, 0xb0,
	0x15, 0xf9, 0xc6, 0xbf, 0x4c, 0xe8, 0x16, 0x14, 0xef, 0x72, 0x47, 0x0c, 0x50, 0xae, 0xc3, 0x39,
	0x92, 0x33, 0x68, 0x17, 0x06, 0x43, 0x0e, 0xab, 0x0c, 0xb5, 0x86, 0xe4, 0x3d, 0xbe, 0x1d, 0xb4,
	0x99, 0x86, 0x36, 0xc8, 0x07, 0x78, 0x58, 0xb5, 0x09, 0x9d, 0xbe, 0xd6, 0x8e, 0x74, 0xfa, 0x7a,
	0xa7, 0xa1, 0x0d, 0x72, 0x01, 0xfb, 0x95, 0x3b, 0x4c, 0x68, 0xf5, 0x8f, 0x75, 0x4e, 0xe1, 0x1d,
	0xde, 0x8a, 0xb9, 0xe6, 0xfe, 0x08, 0x8f, 0xb4, 0xb7, 0x44, 0xb4, 0xb6, 0xea, 0x17, 0xd1, 0x7b,
	0x72, 0x07, 0xea, 0xa6, 0x38, 0xd5, 0x5b, 0xa4, 0x8b, 0x53, 0x6b, 0x13, 0xba, 0x38, 0xf5, 0x17,
	0x91, 0x36, 0x5e, 0x59, 0x17, 0xe5, 0x96, 0x5c, 0xb6, 0xf2, 0xaf, 0xd9, 0xf3, 0xdf, 0x01, 0x00,
	0x00, 0xff, 0xff, 0x6c, 0xb6, 0x1e, 0x06, 0x15, 0x07, 0x00, 0x00,
}
