// Code generated by protoc-gen-go.
// source: hapi/release/release.proto
// DO NOT EDIT!

package release

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import hapi_chart "k8s.io/helm/pkg/proto/hapi/chart"
import hapi_chart3 "k8s.io/helm/pkg/proto/hapi/chart"
import hapi_chart1 "k8s.io/helm/pkg/proto/hapi/chart"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Release describes a deployment of a chart, together with the chart
// and the variables used to deploy that chart.
type Release struct {
	// Name is the name of the release
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	// Info provides information about a release
	Info *Info `protobuf:"bytes,2,opt,name=info" json:"info,omitempty"`
	// Chart is the chart that was released.
	Chart *hapi_chart3.Chart `protobuf:"bytes,3,opt,name=chart" json:"chart,omitempty"`
	// Config is the set of extra Values added to the chart.
	// These values override the default values inside of the chart.
	Config *hapi_chart.Config `protobuf:"bytes,4,opt,name=config" json:"config,omitempty"`
	// Manifest is the string representation of the rendered template.
	Manifest string `protobuf:"bytes,5,opt,name=manifest" json:"manifest,omitempty"`
	// Hooks are all of the hooks declared for this release.
	Hooks []*Hook `protobuf:"bytes,6,rep,name=hooks" json:"hooks,omitempty"`
	// Version is an int32 which represents the version of the release.
	Version int32 `protobuf:"varint,7,opt,name=version" json:"version,omitempty"`
	// Namespace is the kubernetes namespace of the release.
	Namespace string `protobuf:"bytes,8,opt,name=namespace" json:"namespace,omitempty"`
}

func (m *Release) Reset()                    { *m = Release{} }
func (m *Release) String() string            { return proto.CompactTextString(m) }
func (*Release) ProtoMessage()               {}
func (*Release) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

func (m *Release) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Release) GetInfo() *Info {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *Release) GetChart() *hapi_chart3.Chart {
	if m != nil {
		return m.Chart
	}
	return nil
}

func (m *Release) GetConfig() *hapi_chart.Config {
	if m != nil {
		return m.Config
	}
	return nil
}

func (m *Release) GetManifest() string {
	if m != nil {
		return m.Manifest
	}
	return ""
}

func (m *Release) GetHooks() []*Hook {
	if m != nil {
		return m.Hooks
	}
	return nil
}

func (m *Release) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Release) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

// ReleaseSummary summaries a deployment of a chart, together with the chart
// metadata and the variables used to deploy that chart.
type ReleaseSummary struct {
	// Name is the name of the release
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	// Info provides information about a release
	Info *Info `protobuf:"bytes,2,opt,name=info" json:"info,omitempty"`
	// ChartMetadata is the metadata of chart that was released.
	ChartMetadata *hapi_chart1.Metadata `protobuf:"bytes,3,opt,name=chart_metadata,json=chartMetadata" json:"chart_metadata,omitempty"`
	// Config is the set of extra Values added to the chart.
	// These values override the default values inside of the chart.
	Config *hapi_chart.Config `protobuf:"bytes,4,opt,name=config" json:"config,omitempty"`
	// Version is an int32 which represents the version of the release.
	Version int32 `protobuf:"varint,5,opt,name=version" json:"version,omitempty"`
	// Namespace is the kubernetes namespace of the release.
	Namespace string `protobuf:"bytes,6,opt,name=namespace" json:"namespace,omitempty"`
}

func (m *ReleaseSummary) Reset()                    { *m = ReleaseSummary{} }
func (m *ReleaseSummary) String() string            { return proto.CompactTextString(m) }
func (*ReleaseSummary) ProtoMessage()               {}
func (*ReleaseSummary) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{1} }

func (m *ReleaseSummary) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReleaseSummary) GetInfo() *Info {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *ReleaseSummary) GetChartMetadata() *hapi_chart1.Metadata {
	if m != nil {
		return m.ChartMetadata
	}
	return nil
}

func (m *ReleaseSummary) GetConfig() *hapi_chart.Config {
	if m != nil {
		return m.Config
	}
	return nil
}

func (m *ReleaseSummary) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *ReleaseSummary) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func init() {
	proto.RegisterType((*Release)(nil), "hapi.release.Release")
	proto.RegisterType((*ReleaseSummary)(nil), "hapi.release.ReleaseSummary")
}

func init() { proto.RegisterFile("hapi/release/release.proto", fileDescriptor2) }

var fileDescriptor2 = []byte{
	// 324 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x92, 0x3d, 0x4b, 0xfc, 0x40,
	0x10, 0xc6, 0xc9, 0x5d, 0x5e, 0x2e, 0xf3, 0xff, 0x7b, 0xe0, 0x20, 0xba, 0x06, 0x8b, 0x70, 0x85,
	0x06, 0x8b, 0x1c, 0x68, 0x69, 0xa7, 0x8d, 0x16, 0x36, 0x6b, 0x67, 0x23, 0x6b, 0xdc, 0x98, 0x70,
	0x66, 0x37, 0x24, 0x51, 0xf0, 0x9b, 0xf8, 0x25, 0xfd, 0x0e, 0xb2, 0x2f, 0xd1, 0xbd, 0x13, 0x04,
	0xb1, 0xd9, 0x64, 0xe6, 0xf7, 0xb0, 0xf3, 0xcc, 0x93, 0x40, 0x52, 0xb1, 0xb6, 0x5e, 0x76, 0xfc,
	0x89, 0xb3, 0x9e, 0x8f, 0xcf, 0xbc, 0xed, 0xe4, 0x20, 0xf1, 0xbf, 0x62, 0xb9, 0xed, 0x25, 0x7b,
	0x6b, 0xca, 0x4a, 0xca, 0x95, 0x91, 0x6d, 0x80, 0x5a, 0x94, 0x72, 0x0d, 0x14, 0x15, 0xeb, 0x86,
	0x65, 0x21, 0x45, 0x59, 0x3f, 0x5a, 0xb0, 0xeb, 0x02, 0x75, 0xda, 0xfe, 0xbe, 0xd3, 0x6f, 0xf8,
	0xc0, 0x1e, 0xd8, 0xc0, 0x0c, 0x5a, 0xbc, 0x4d, 0x20, 0xa2, 0x66, 0x04, 0x22, 0xf8, 0x82, 0x35,
	0x9c, 0x78, 0xa9, 0x97, 0xc5, 0x54, 0xbf, 0xe3, 0x21, 0xf8, 0x6a, 0x32, 0x99, 0xa4, 0x5e, 0xf6,
	0xef, 0x04, 0x73, 0xd7, 0x7a, 0x7e, 0x25, 0x4a, 0x49, 0x35, 0xc7, 0x23, 0x08, 0xf4, 0xfd, 0x64,
	0xaa, 0x85, 0xdb, 0x46, 0x68, 0x4c, 0x5c, 0xa8, 0x93, 0x1a, 0x8e, 0xc7, 0x10, 0x1a, 0xcf, 0xc4,
	0x77, 0xaf, 0xb4, 0x4a, 0x4d, 0xa8, 0x55, 0x60, 0x02, 0xb3, 0x86, 0x89, 0xba, 0xe4, 0xfd, 0x40,
	0x02, 0x6d, 0xea, 0xb3, 0xc6, 0x0c, 0x02, 0x95, 0x55, 0x4f, 0xc2, 0x74, 0xfa, 0xdd, 0xd9, 0xa5,
	0x94, 0x2b, 0x6a, 0x04, 0x48, 0x20, 0x7a, 0xe1, 0x5d, 0x5f, 0x4b, 0x41, 0xa2, 0xd4, 0xcb, 0x02,
	0x3a, 0x96, 0x78, 0x00, 0xb1, 0x5a, 0xb2, 0x6f, 0x59, 0xc1, 0xc9, 0x4c, 0x0f, 0xf8, 0x6a, 0x2c,
	0xde, 0x3d, 0x98, 0xdb, 0x68, 0x6e, 0x9e, 0x9b, 0x86, 0x75, 0xaf, 0x7f, 0x4a, 0xe8, 0x0c, 0xe6,
	0x7a, 0xc9, 0xbb, 0xf1, 0x0b, 0xd8, 0xa8, 0x76, 0xdc, 0x00, 0xae, 0x2d, 0xa3, 0x5b, 0xba, 0x1e,
	0xcb, 0x5f, 0xa5, 0xe6, 0xec, 0x1b, 0xfc, 0xb0, 0x6f, 0xb8, 0xb1, 0xef, 0x79, 0x7c, 0x1b, 0x59,
	0xdb, 0xf7, 0xa1, 0xfe, 0x39, 0x4e, 0x3f, 0x02, 0x00, 0x00, 0xff, 0xff, 0xcf, 0xa5, 0xc6, 0x66,
	0xc6, 0x02, 0x00, 0x00,
}
