//go:build ignore

/*
Copyright The Helm Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This program regenerates zz_generated_known_versions.go, the built-in
// Kubernetes API group/versions that seed the default capability version set.
//
// It enumerates client-go's runtime scheme plus the apiextensions groups —
// exactly as pkg/chart/common used to do at runtime — and writes the result as
// a static slice. Doing this at generate time keeps client-go, k8s.io/api and
// apiextensions-apiserver out of the runtime dependency graph of every binary
// that links Helm's chart packages.
//
// Run via `go generate ./pkg/chart/common/...`.
package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"

	apiextensionsv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	apiextensionsv1beta1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1"
	"k8s.io/client-go/kubernetes/scheme"
)

const target = "zz_generated_known_versions.go"

func main() {
	// Register the built-in extension APIs as well so CRDs are supported in the
	// default version set. This has caused problems with `helm template` in the
	// past, so let's be safe.
	if err := apiextensionsv1beta1.AddToScheme(scheme.Scheme); err != nil {
		fatal(err)
	}
	if err := apiextensionsv1.AddToScheme(scheme.Scheme); err != nil {
		fatal(err)
	}

	var buf bytes.Buffer
	buf.WriteString(`/*
Copyright The Helm Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by gen_known_versions.go; DO NOT EDIT.

package common

// defaultKnownVersions is the set of built-in Kubernetes API group/versions
// used to seed the default capability version set. Regenerate with
// go generate ./pkg/chart/common/... after a client-go bump.
var defaultKnownVersions = VersionSet{
`)
	for _, gv := range scheme.Scheme.PrioritizedVersionsAllGroups() {
		fmt.Fprintf(&buf, "\t%q,\n", gv.String())
	}
	buf.WriteString("}\n")

	out, err := format.Source(buf.Bytes())
	if err != nil {
		fatal(err)
	}
	if err := os.WriteFile(target, out, 0o644); err != nil {
		fatal(err)
	}
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, "gen_known_versions:", err)
	os.Exit(1)
}
