apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitoring
  template:
    metadata:
      labels:
        app: monitoring
    spec:
      containers:
        - name: monitoring
          image: busybox:1.36
          command: ["sh", "-c", "echo 'monitoring running' && sleep 3600"]
