name: Label PRs
on:
  pull_request_target:
    types: [opened]
permissions: {}
jobs:
  label:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@8558fd74291d67161a8a78ce36a881fa63b766a9 # pin@v5.0.0
        with:
          sync-labels: true
