name: "Shuffle test"
on:
  schedule:
  - cron: "45 1 * * *"
    branches:
      - "main"

permissions:
  contents: read

jobs:
  shuffle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # pin@v5.0.0
      - name: Add variables to environment file
        run: cat ".github/env" >> "$GITHUB_ENV"
      - name: Setup Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # pin@5.5.0
        with:
          go-version: '${{ env.GOLANG_VERSION }}'
          check-latest: true
      - name: Test shuffle
        run: make test-unit TESTFLAGS="-shuffle=on -count=2"
